spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://gulimall-mysql.gulimall:3306/gulimall_ums?useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: gulimall-member  # 给这个服务起个名字 （这样Nacos注册中心就能发现这个服务了）
  cloud:
    nacos:
      discovery:
        server-addr: gulimall-nacos.gulimall:8848  # nacos注册中心的地址

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml  # 寻找mapper文件
  global-config:
    db-config:
      id-type: auto  # 主键自增
server:
  port: 8080