spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.100.135:3306/gulimall_pms?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # Nacos注册中心的地址
        server-addr: 192.168.100.135:8848
  jackson:
    # 指定格式化的规则
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    # 开启thymeleaf 的缓存
    cache: true




mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml  # 寻找mapper文件
  global-config:
    db-config:
      id-type: auto  # 主键自增
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
server:
  port: 10000
# 调整日志级别
logging:
  level:
    com.example.gulimall: error



