spring:
  cloud:
    gateway:
      routes:
#        - id: test_route
#          uri: https://www.baidu.com/
#          predicates:
#            - Query=url,baidu
#        - id: qq_route
#          uri: https://www.qq.com/
#          predicates:
#            - Query=url,qq

        # 路由规则   【 只要发送 /api/product/** 格式的任意请求 ， 就会默认先路由到 gulimall-product 服务， 并且会把路径 /api/** 重写成 /**  】
        - id: product_route
          # lb 代表负载均衡  【 lb://服务名 】
          uri: lb://gulimall-product
          predicates:
            # 按照路径断言    前端项目，都加上 /api
            - Path=/api/product/**
          filters:
            # 路径重写   【 将 /api/(?<segment>.*) 路径 自动重写成 /$\{segment} 路径  】
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        # 路由规则   【 只要发送 /api/product/** 格式的任意请求 ， 就会默认先路由到 gulimall-member 服务， 并且会把路径 /api/** 重写成 /**  】
        - id: member_route
          # lb 代表负载均衡  【 lb://服务名 】
          uri: lb://gulimall-member
          predicates:
            # 按照路径断言    前端项目，都加上 /api
            - Path=/api/member/**
          filters:
            # 路径重写   【 将 /api/(?<segment>.*) 路径 自动重写成 /$\{segment} 路径  】
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        # 路由规则   【 只要发送 /api/product/** 格式的任意请求 ， 就会默认先路由到 gulimall-ware 服务， 并且会把路径 /api/** 重写成 /**  】
        - id: ware_route
          # lb 代表负载均衡  【 lb://服务名 】
          uri: lb://gulimall-ware
          predicates:
            # 按照路径断言    前端项目，都加上 /api
            - Path=/api/ware/**
          filters:
            # 路径重写   【 将 /api/(?<segment>.*) 路径 自动重写成 /$\{segment} 路径  】
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        # 路由规则   【 只要发送 /api/** 格式的任意请求 ， 就会默认先路由到 renren-fast 服务， 并且会把路径 /api/** 重写成 /renren-fast/**  】
        - id: admin_route
          # lb 代表负载均衡  【 lb://服务名 】
          uri: lb://renren-fast
          # 断言规则
          predicates:
            # 按照路径断言    前端项目，都加上 /api
            - Path=/api/**
          filters:
            # 路径重写   【 将 /api/(?<segment>.*) 路径 自动重写成 /renren-fast/$\{segment} 路径  】
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}



        - id: gulimall_host_route
          uri: lb://gulimall-product
          predicates:
            # 只要 请求体的Host中的值是 gulimall.com 或者 item.gulimall.com 就匹配到gulimall-product服务
            - Host=gulimall.com,item.gulimall.com

        - id: gulimall_search_route
          uri: lb://gulimall-search
          predicates:
            # 只要 请求体的Host中的值是 search.gulimall.com 就匹配到gulimall-search服务
            - Host=search.gulimall.com

        - id: gulimall_auth_route
          uri: lb://gulimall-auth-server
          predicates:
            # 只要 请求体的Host中的值是 auth.gulimall.com 就匹配到gulimall-auth-server服务
            - Host=auth.gulimall.com

        - id: gulimall_cart_route
          uri: lb://gulimall-cart
          predicates:
            # 只要 请求体的Host中的值是 cart.gulimall.com 就匹配到gulimall-cart服务
            - Host=cart.gulimall.com

        - id: gulimall_order_route
          uri: lb://gulimall-order
          predicates:
            # 只要 请求体的Host中的值是 order.gulimall.com 就匹配到gulimall-order服务
            - Host=order.gulimall.com

