server:
  port: 8080


spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://gulimall-mysql.gulimall:3306/gulimall_wms?useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # Nacos 注册中心地址
        server-addr: gulimall-nacos.gulimall:8848

  application:
    name: gulimall-ware
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml  # 寻找mapper文件
  global-config:
    db-config:
      id-type: auto  # 主键自增

logging:
  level:
    com.example: debug
